Structure back-end
PiedTeam/DreameCloneTraining-BE-Project pull request #20
Opened 2024-04-09 10:00 UTC by huy1707developer

Structure back-end

2024-04-09 11:04 UTC, nnh53 commented
@huy1707developer pls revert your commit or change your commit name follow by the convention in QUY_TẮC_COMMIT.md

2024-04-09 17:09 UTC, nnh53 reviewed
fix alot pls

2024-04-09 17:09 UTC, nnh53 commented on src/index.ts
> +import YAML from 'yaml'
pls remove unused import

2024-04-09 17:09 UTC, nnh53 commented on src/index.ts
> +  origin: 'http://localhost:4000' || 'http://localhost:5173',
make this to ENV

2024-04-09 17:09 UTC, nnh53 commented on src/index.ts
> +  console.log(`server này đang chạy trên port:::${PORT}`)
just one :

2024-04-09 17:09 UTC, nnh53 commented on .eslintrc
> +        "jsxSingleQuote": true
are you sure ?? we just use ts

2024-04-09 17:09 UTC, nnh53 commented on .gitattributes
> +/.pnp.*              binary linguist-generated
what is this file for

2024-04-09 17:09 UTC, nnh53 commented on .prettierrc
> +  "semi": false,
revert the tab

2024-04-09 17:09 UTC, nnh53 commented on package-lock.json
> +  "name": "backend",
we use yarn-lock not package-lock

2024-04-09 17:09 UTC, nnh53 commented on tsconfig.json
> +    "module": "CommonJS", // Quy định output module được sử dụng
remove unnecessary comment, only leave what you need

2024-04-09 17:09 UTC, nnh53 commented on .yarnrc.yml
> +
what is this file for

2024-04-09 17:12 UTC, nnh53 requested changes
test request change, and please remove the learn-swagger file

2024-04-09 18:51 UTC, nnh53 commented on package.json
> +  "name": "dreame-backend",
fix to this "dreame-clone-training-be", just to be carefull @@

2024-04-09 18:57 UTC, nnh53 commented on package.json
> +  "packageManager": "yarn@4.1.1",
image.png, this is just a Experimental feature

2024-04-09 19:00 UTC, nnh53 commented on package.json
> +  "license": "MIT",
"author": "",
"license": "MIT"
remove these 2 and at this at the top
"private": true,

2024-04-09 19:01 UTC, nnh53 commented
@CiscoTran can you help him

2024-04-10 15:15 UTC, huy1707developer commented
@lcaohoanq, can you review for me?

2024-04-10 15:20 UTC, lcaohoanq commented
> @lcaohoanq, can you review for me?

No, i can't the reviewer is only
![image](https://github.com/PiedTeam/DreameCloneTraining-BE-Project/assets/136492579/7de31d10-fa20-4ce6-93d5-0d63b858c3a3)

2024-04-10 16:12 UTC, nnh53 commented
@huy1707developer it your PR, you can add more people to review to, or is it only me can add reviewer ??

2024-04-11 09:52 UTC, lcaohoanq submitted a review, later dismissed
@huy1707developer 
I've done review your PR

2024-04-11 09:59 UTC, lcaohoanq approved these changes

2024-04-11 10:01 UTC, lcaohoanq approved these changes

2024-04-11 10:03 UTC, lcaohoanq approved these changes, later dismissed

2024-04-11 13:31 UTC, minhhy2801 commented on .eslintrc
> +        "semi": false,
```suggestion
        "semi": true,
```

2024-04-11 13:31 UTC, minhhy2801 commented on .eslintrc
> +        "trailingComma": "none",
should have

2024-04-11 13:32 UTC, minhhy2801 commented on .gitignore
> +!.yarn/versions
You didn't use them

2024-04-11 13:34 UTC, minhhy2801 commented on src/index.ts
> +}
add type for them

2024-04-11 13:34 UTC, minhhy2801 commented on tsconfig.json
> +    "module": "CommonJS",
why do you pick CommonJS here?

2024-04-14 18:10 UTC, nnh53 submitted a review, later dismissed

2024-04-14 18:43 UTC, nnh53 approved these changes

2024-04-14 18:46 UTC, merged